export const URL = "https://palmapi.blackneb.com/api/"
export const ADD_USER_INFORMATION = "ADD_USER_INFORMATION"
export const ADD_USERS_LIST = "ADD_USERS_LIST"
export const USER_LOGGED = "USER_LOGGED"
export const PALM_IMAGE_DETAILS = "PALM_IMAGE_DETAILS"
export const HARVESTERS_LIST = "HARVESTERS_LIST"